import { existsSync, readFileSync } from "node:fs";
import {
  chmod,
  mkdir,
  readFile,
  rename,
  unlink,
  writeFile,
} from "node:fs/promises";
import { join, sep } from "node:path";
import { spawnSync } from "node:child_process";

const HOOK_NAME = "pre-commit";
const BACKUP_SUFFIX = ".unmask-original";
const SIGNATURE = "# unmask pre-commit hook";

export interface InstallResult {
  path: string;
  chained: boolean;
}

export class HookInstallError extends Error {}

export async function installHook(rootDir: string): Promise<InstallResult> {
  const hooksPath = resolveHooksPath(rootDir);

  if (hooksPath.kind === "custom") {
    throw new HookInstallError(
      `git is configured with a custom core.hooksPath ("${hooksPath.path}"). ` +
        `unmask cannot install there safely. ` +
        `Add "${HOOK_NAME}" to your hook manager manually, or run ` +
        `\`git config --unset core.hooksPath\` and retry.`,
    );
  }

  const hooksDir = hooksPath.path;
  await mkdir(hooksDir, { recursive: true });

  const hookPath = join(hooksDir, HOOK_NAME);
  const backupPath = `${hookPath}${BACKUP_SUFFIX}`;

  if (existsSync(hookPath)) {
    const existing = await readFile(hookPath, "utf-8");
    if (!existing.includes(SIGNATURE)) {
      await rename(hookPath, backupPath);
    }
  }

  // Chaining is determined by whether a backup exists, not by whether
  // we just created one. On a re-install over our own hook, the backup
  // from the previous install is still there and must still be chained.
  const chained = existsSync(backupPath);

  const script = buildHookScript(chained);
  await writeFile(hookPath, script, { mode: 0o755 });
  await chmod(hookPath, 0o755);

  return { path: toPosix(hookPath), chained };
}

export async function uninstallHook(rootDir: string): Promise<void> {
  const hooksPath = resolveHooksPath(rootDir);
  const hookPath = join(hooksPath.path, HOOK_NAME);
  const backupPath = `${hookPath}${BACKUP_SUFFIX}`;

  if (!existsSync(hookPath)) return;

  const existing = await readFile(hookPath, "utf-8");
  if (!existing.includes(SIGNATURE)) {
    throw new HookInstallError(
      `The hook at ${hookPath} was not installed by unmask. Refusing to remove it.`,
    );
  }

  await unlink(hookPath);

  if (existsSync(backupPath)) {
    await rename(backupPath, hookPath);
    await chmod(hookPath, 0o755);
  }
}

export function isHookInstalled(rootDir: string): boolean {
  const hookPath = join(resolveHooksPath(rootDir).path, HOOK_NAME);
  if (!existsSync(hookPath)) return false;
  try {
    return readFileSync(hookPath, "utf-8").includes(SIGNATURE);
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------

type HooksPath =
  | { kind: "default"; path: string }
  | { kind: "custom"; path: string };

function resolveHooksPath(rootDir: string): HooksPath {
  const gitDirResult = spawnSync("git", ["rev-parse", "--git-dir"], {
    cwd: rootDir,
    encoding: "utf-8",
  });
  if (gitDirResult.status !== 0) {
    throw new HookInstallError(`${rootDir} is not inside a git repository.`);
  }

  const configured = spawnSync("git", ["config", "--get", "core.hooksPath"], {
    cwd: rootDir,
    encoding: "utf-8",
  });

  if (configured.status === 0 && configured.stdout.trim()) {
    return { kind: "custom", path: configured.stdout.trim() };
  }

  const gitDir = gitDirResult.stdout.trim();
  const absoluteGitDir = gitDir.startsWith("/")
    ? gitDir
    : join(rootDir, gitDir);
  return { kind: "default", path: join(absoluteGitDir, "hooks") };
}

function buildHookScript(chained: boolean): string {
  const lines: string[] = [
    "#!/bin/sh",
    SIGNATURE,
    "#",
    "# This file was generated by `unmask install`. Do not edit by hand.",
    "# To update, re-run `unmask install`. To remove, run `unmask uninstall`.",
    "",
  ];

  if (chained) {
    lines.push(
      "# A pre-existing hook was renamed to `pre-commit.unmask-original`.",
      "# It runs first; if it fails, the commit is aborted before unmask runs.",
      'ORIGINAL="$(dirname "$0")/pre-commit.unmask-original"',
      'if [ -x "$ORIGINAL" ]; then',
      '  "$ORIGINAL" "$@" || exit $?',
      "fi",
      "",
    );
  }

  lines.push(
    "# Find the unmask binary. Prefer a local install; fall back to PATH.",
    'if [ -x "node_modules/.bin/unmask" ]; then',
    "  BIN=node_modules/.bin/unmask",
    "elif command -v unmask >/dev/null 2>&1; then",
    "  BIN=unmask",
    "else",
    '  echo "unmask: not installed locally, skipping pre-commit scan" >&2',
    "  exit 0",
    "fi",
    "",
    "# --quiet suppresses the summary on clean scans.",
    '"$BIN" scan --staged --quiet',
    "exit $?",
    "",
  );

  return lines.join("\n");
}

/**
 * Normalize a filesystem path to forward slashes. Matches the project-
 * wide convention (Finding.file, SkippedFile.path) and lets callers
 * compare paths with simple string equality, regardless of platform.
 */
function toPosix(p: string): string {
  return p.split(sep).join("/");
}
